// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import ExampleController from "./example_controller"
application.register("example", ExampleController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SlideoverController from "./slideover_controller"
application.register("slideover", SlideoverController)
